# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#


version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  shopizer-ci:
    docker:
      - image: shopizerecomm/ci:latest
        auth:
          username: shopizerecomm
          password: $DOCKERHUB_PASSWORD  
      
working_directory: /tmp


# Define the jobs we want to run for this project
jobs:
  build:
    executor: shopizer-ci
    # checkout and run unit tests
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            set -x
            /home/shopizer/tools/shopizer.sh tests
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  publish:
    executor: shopizer-ci
    steps:
       - attach_workspace:
          at: .
       # start proprietary DB using private Docker image
       # with credentials stored in the UI
      - run:
          name: Run publish
          command: |
            set -x
            /home/shopizer/tools/shopizer.sh publish

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build
      - publish:
          requires:
            - build